In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
sns.set_style("whitegrid")
plt.style.use("fivethirtyeight")

In [2]:
df = pd.read_csv("Diabetes_Final_Data_V2.csv")
df

age  gender  pulse_rate  systolic_bp  diastolic_bp  glucose  height  \
0      42  Female          66          110            73     5.88    1.65   
1      35  Female          60          125            68     5.71    1.47   
2      62  Female          57          127            74     6.85    1.52   
3      73    Male          55          193           112     6.28    1.63   
4      68  Female          71          150            81     5.71    1.42   
...   ...     ...         ...          ...           ...      ...     ...   
5432   74    Male          83          164            89     6.47    1.60   
5433   75    Male          67          141           104     8.31    1.65   
5434   40  Female          67          134           114     7.61    1.50   
5435   36  Female          62          139            80     4.90    1.52   
5436   26  Female          80          134            93     5.15    1.47   

      weight    bmi  family_diabetes  hypertensive  family_hypertension  \
0       70.2  25.75                0             0                    0   
1       42.5  19.58                0             0                    0   
2       47.0  20.24                0             0                    0   
3       57.4  21.72                0             0                    0   
4       36.0  17.79                0             0                    0   
...      ...    ...              ...           ...                  ...   
5432    64.0  24.99                0             1                    0   
5433    62.0  22.75                0             0                    0   
5434    69.0  30.72                0             1                    0   
5435    41.5  17.87                0             0                    0   
5436    67.1  30.92                0             0                    0   

      cardiovascular_disease  stroke diabetic  
0                          0       0       No  
1                          0       0       No  
2                          0       0       No  
3                          0       0       No  
4                          0       0       No  
...                      ...     ...      ...  
5432                       1       0       No  
5433                       0       0      Yes  
5434                       0       1       No  
5435                       0       0       No  
5436                       0       0       No  

[5437 rows x 15 columns]

In [3]:
df['diabetic'].value_counts()

No     5093
Yes     344
Name: diabetic, dtype: int64

In [34]:
# Check for null values
null_values = df.isnull().sum()

print("Null values in the dataset:")
print(null_values)

Null values in the dataset:
age                       0
gender                    0
pulse_rate                0
systolic_bp               0
diastolic_bp              0
glucose                   0
height                    0
weight                    0
bmi                       0
family_diabetes           0
hypertensive              0
family_hypertension       0
cardiovascular_disease    0
stroke                    0
diabetic                  0
dtype: int64


In [27]:
df['diabetic'].value_counts()

No     5093
Yes     344
Name: diabetic, dtype: int64

In [28]:
df['gender'].replace(['Female', 'Male' ],
                        [0, 1], inplace=True)


df['diabetic'].replace(['No', 'Yes'],
                        [0, 1], inplace=True)

In [29]:
df.columns

Index(['age', 'gender', 'pulse_rate', 'systolic_bp', 'diastolic_bp', 'glucose',
       'height', 'weight', 'bmi', 'family_diabetes', 'hypertensive',
       'family_hypertension', 'cardiovascular_disease', 'stroke', 'diabetic'],
      dtype='object')

In [30]:
import numpy as np



# Calculate Pearson correlation coefficient
correlation_coef = np.corrcoef(df['age'], df['stroke'])[0, 1]

print("Pearson correlation coefficient:", correlation_coef)


Pearson correlation coefficient: 0.051836464887361614


In [31]:
import pandas as pd
import scipy.stats as stats

# Load the dataset
#df = pd.read_csv('your_dataset.csv')  # Replace 'your_dataset.csv' with the actual filename and path
df=df[df['diabetic']==0]
# Continuous variables
continuous_vars = ['age', 'pulse_rate', 'systolic_bp', 'diastolic_bp', 'glucose', 'height', 'weight', 'bmi']
continuous_stats = df[continuous_vars].describe().loc[['mean', 'std']].T
continuous_stats['mean ± SD'] = continuous_stats['mean'].round(2).astype(str) + ' ± ' + continuous_stats['std'].round(2).astype(str)
continuous_stats.drop(['mean', 'std'], axis=1, inplace=True)
print("Mean ± SD for continuous variables:")
print(continuous_stats)

# Categorical variables
categorical_vars = ['gender', 'family_diabetes', 'hypertensive', 'family_hypertension', 'cardiovascular_disease', 'stroke', 'diabetic']
categorical_stats = {}
for var in categorical_vars:
    freq = df[var].value_counts(normalize=True) * 100
    categorical_stats[var] = freq.round(2)
categorical_stats = pd.DataFrame(categorical_stats)
print("\nFrequency (%) for categorical variables:")
print(categorical_stats)

# Statistical tests
independent_t_results = {}
chi_square_results = {}

# Perform independent t-tests
for var in continuous_vars:
    t_stat, p_value = stats.ttest_ind(df[df['diabetic'] == 1][var], df[df['diabetic'] == 0][var])
    independent_t_results[var] = {'t-statistic': t_stat, 'p-value': p_value}

# Perform chi-square tests
for var in categorical_vars:
    contingency_table = pd.crosstab(df['diabetic'], df[var])
    chi2, p_value, _, _ = stats.chi2_contingency(contingency_table)
    chi_square_results[var] = {'chi-square': chi2, 'p-value': p_value}

print("\nIndependent t-test results:")
for var, results in independent_t_results.items():
    print(f"{var}: t-statistic={results['t-statistic']:.2f}, p-value={results['p-value']:.4f}")

print("\nChi-square test results:")
for var, results in chi_square_results.items():
    print(f"{var}: chi-square={results['chi-square']:.2f}, p-value={results['p-value']:.4f}")


Mean ± SD for continuous variables:
                   mean ± SD
age             45.21 ± 14.4
pulse_rate     76.62 ± 12.19
systolic_bp   132.96 ± 21.98
diastolic_bp   81.56 ± 12.32
glucose          7.31 ± 2.51
height           1.55 ± 0.08
weight         53.34 ± 10.04
bmi             22.37 ± 8.99

Frequency (%) for categorical variables:
   gender  family_diabetes  hypertensive  family_hypertension  \
0   71.29            96.15         91.89                95.96   
1   28.71             3.85          8.11                 4.04   

   cardiovascular_disease  stroke  diabetic  
0                    99.1   99.69     100.0  
1                     0.9    0.31       NaN  

Independent t-test results:
age: t-statistic=nan, p-value=nan
pulse_rate: t-statistic=nan, p-value=nan
systolic_bp: t-statistic=nan, p-value=nan
diastolic_bp: t-statistic=nan, p-value=nan
glucose: t-statistic=nan, p-value=nan
height: t-statistic=nan, p-value=nan
weight: t-statistic=nan, p-value=nan
bmi: t-statistic=nan, p-va

In [6]:
features = ['age', 'gender', 'pulse_rate', 'systolic_bp', 'diastolic_bp', 'glucose',
       'height', 'weight', 'bmi', 'family_diabetes', 'hypertensive',
       'family_hypertension', 'cardiovascular_disease', 'stroke', 'diabetic']

In [7]:
diabetes_df =df

In [18]:
# Perform independent t-test for continuous variables
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind, chi2_contingency
continuous_vars = ['age', 'pulse_rate', 'systolic_bp', 'diastolic_bp', 'glucose','height', 'weight', 'bmi',]
for var in continuous_vars:
    #diabetic_vals = df[df['diabetic'] == 'No'][var]
    #non_diabetic_vals = df[df['diabetic'] == 'Yes'][var]
    #contingency_table = pd.crosstab(df['diabetic'], df[var])
    t_stat, p_value = ttest_ind(df['diabetic'], df[var])
    p_value = round(p_value, 6)
    if p_value < 0.05:
        print(f"Variable '{var}' is significantly associated with diabetes (p-value={p_value}).")


Variable 'age' is significantly associated with diabetes (p-value=0.0).
Variable 'pulse_rate' is significantly associated with diabetes (p-value=0.0).
Variable 'systolic_bp' is significantly associated with diabetes (p-value=0.0).
Variable 'diastolic_bp' is significantly associated with diabetes (p-value=0.0).
Variable 'glucose' is significantly associated with diabetes (p-value=0.0).
Variable 'height' is significantly associated with diabetes (p-value=0.0).
Variable 'weight' is significantly associated with diabetes (p-value=0.0).
Variable 'bmi' is significantly associated with diabetes (p-value=0.0).


In [12]:
# Perform chi-square test for categorical variables
categorical_vars = ['gender', 'family_diabetes', 'hypertensive',
       'family_hypertension', 'cardiovascular_disease', 'stroke']
for var in categorical_vars:
    contingency_table = pd.crosstab(df['diabetic'], df[var])
    chi2, p_value, _, _ = chi2_contingency(contingency_table)
    if p_value < 0.05:
        print(f"Variable '{var}' is significantly associated with diabetes (p-value={p_value}).")

Variable 'hypertensive' is significantly associated with diabetes (p-value=1.1992870979713135e-148).
Variable 'cardiovascular_disease' is significantly associated with diabetes (p-value=7.316469531822227e-11).
Variable 'stroke' is significantly associated with diabetes (p-value=0.03975765802490102).


In [13]:
import pandas as pd
from tabulate import tabulate
# Initialize an empty list to store the statistics for each feature
statistics = []

# Iterate over each feature and extract the statistics
for feature in features:
    distinct_count = diabetes_df[feature].nunique() / len(diabetes_df) * 100
    mean = diabetes_df[feature].mean()
    data_range = diabetes_df[feature].max() - diabetes_df[feature].min()
    zeros_percent = (diabetes_df[feature] == 0).mean() * 100
    percentile_5th = diabetes_df[feature].quantile(0.05)
    q1 = diabetes_df[feature].quantile(0.25)
    median = diabetes_df[feature].median()
    q3 = diabetes_df[feature].quantile(0.75)
    percentile_95th = diabetes_df[feature].quantile(0.95)
    value_range = diabetes_df[feature].max() - diabetes_df[feature].min()
    iqr = q3 - q1
    std_dev = diabetes_df[feature].std()
    coefficient_of_variation = std_dev / mean
    kurtosis = diabetes_df[feature].kurtosis()
    mad = diabetes_df[feature].mad()
    skewness = diabetes_df[feature].skew()
    total_sum = diabetes_df[feature].sum()
    variance = diabetes_df[feature].var()
    memory_size = diabetes_df[feature].memory_usage(index=False) / 1024  # in KB

    # Append the statistics for the current feature to the list
    statistics.append([feature, distinct_count, mean, data_range, zeros_percent,
                       percentile_5th, q1, median, q3, percentile_95th, value_range,
                       iqr, std_dev, coefficient_of_variation, kurtosis, mad,
                       skewness, total_sum, variance, memory_size])

# Create a DataFrame from the list of statistics
statistics_df = pd.DataFrame(statistics, columns=['Feature', 'Distinct count Unique (%)', 'Mean', 'Range', 'Zeros (%)',
                                                  '5th percentile', 'Q1', 'Median', 'Q3', '95th percentile',
                                                  'Range', 'IQR', 'Standard deviation', 'Coefficient of variation',
                                                  'Kurtosis', 'MAD', 'Skewness', 'Sum', 'Variance', 'Memory size'])

# Convert the DataFrame to a tabular format
table = tabulate(statistics_df, headers='keys', tablefmt='psql')

# Print the tabular format
print(table)



+----+------------------------+-----------------------------+-------------+---------+-------------+------------------+--------+----------+--------+-------------------+---------+-------+----------------------+----------------------------+--------------+-------------+------------+-----------+--------------+---------------+
|    | Feature                |   Distinct count Unique (%) |        Mean |   Range |   Zeros (%) |   5th percentile |     Q1 |   Median |     Q3 |   95th percentile |   Range |   IQR |   Standard deviation |   Coefficient of variation |     Kurtosis |         MAD |   Skewness |       Sum |     Variance |   Memory size |
|----+------------------------+-----------------------------+-------------+---------+-------------+------------------+--------+----------+--------+-------------------+---------+-------+----------------------+----------------------------+--------------+-------------+------------+-----------+--------------+---------------|
|  0 | age                    |

In [15]:
statistics_df.to_csv("Data_Description.csv")

In [17]:
y = df['diabetic'].values
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [18]:
x = df.drop(['diabetic'],axis=1)

In [19]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import AdaBoostClassifier, BaggingClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from statistics import mean

In [20]:
from sklearn.feature_selection import SelectKBest, f_classif

# Set the threshold value
threshold = 10

# Initialize SelectKBest with f_classif score function
selector = SelectKBest(score_func=f_classif)

# Fit the selector on the data
selector.fit(x, y)

# Get the scores and p-values
scores = selector.scores_
p_values = selector.pvalues_

# Set the threshold and select features above the threshold
selected_features = x.columns[scores > threshold]

print(selected_features )

Index(['age', 'pulse_rate', 'systolic_bp', 'diastolic_bp', 'glucose', 'weight',
       'hypertensive', 'cardiovascular_disease'],
      dtype='object')


In [21]:
#selected_features = ['age', 'systolic_bp', 'diastolic_bp', 'glucose', 'weight', 'hypertensive', 'cardiovascular_disease']
X_selected = x[selected_features]


In [22]:
# Print the selected feature names and their scores
# Sort the scores in descending order
sorted_indices = np.argsort(scores)[::-1]
sorted_scores = scores[sorted_indices]
for feature, score in zip(selected_features, sorted_scores):
    print("Feature:", feature)
    print("Score:", score)
    print()

Feature: age
Score: 775.4406486136395

Feature: pulse_rate
Score: 559.164933774742

Feature: systolic_bp
Score: 136.86608207501098

Feature: diastolic_bp
Score: 134.2668933031381

Feature: glucose
Score: 64.3312763261427

Feature: weight
Score: 46.26464811325997

Feature: hypertensive
Score: 42.02976328131725

Feature: cardiovascular_disease
Score: 11.531994554390288



In [23]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
X_selected, y = ros.fit_resample(X_selected, y)
#X_test, y_test = ros.fit_resample(X_test, y_test)

from collections import Counter

print(f"Training target statistics: {Counter(y)}")
#print(f"Testing target statistics: {Counter(y_test)}")

Training target statistics: Counter({0: 5093, 1: 5093})


In [24]:
# Feature selection using Correlation Feature Selection coupled with Forest Panelized Attributes (CFS–FPA)
#selector = SelectKBest(score_func=f_classif, k=10)
#X_selected = selector.fit_transform(x, y)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

In [27]:
#from imblearn.combine import SMOTETomek

#smote_tomek = SMOTETomek(random_state=42)
#X_train, y_train = smote_tomek.fit_resample(X_train, y_train)


In [28]:
# from imblearn.combine import SMOTEENN

# smote_enn = SMOTEENN(random_state=42)
# X_train, y_train = smote_enn.fit_resample(X_train, y_train)


In [14]:
# from imblearn.over_sampling import ADASYN

# adasyn = ADASYN(random_state=42)
# X_train, y_train = adasyn.fit_resample(X_train, y_train)


In [15]:
# from imblearn.under_sampling import RandomUnderSampler

# rus = RandomUnderSampler(random_state=42)
# X_train, y_train = rus.fit_resample(X_train, y_train)


In [16]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
X_train, y_train = ros.fit_resample(X_train, y_train)
#X_test, y_test = ros.fit_resample(X_test, y_test)

from collections import Counter

print(f"Training target statistics: {Counter(y_train)}")
print(f"Testing target statistics: {Counter(y_test)}")

Training target statistics: Counter({0: 4074, 1: 4074})
Testing target statistics: Counter({0: 1019, 1: 69})


In [17]:
# from imblearn.over_sampling import SMOTE
# # create SMOTE object
# smote = SMOTE(random_state=42)

# # resample the training data using SMOTE
# X_train, y_train = smote.fit_resample(X_train, y_train)
# from sklearn.model_selection import train_test_split
# from collections import Counter

# print(f"Training target statistics: {Counter(y_train)}")
# print(f"Testing target statistics: {Counter(y_test)}")

In [29]:
# Standardize the input features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [26]:
# AdaBoosting

# Support Vector Machine (SVM)
svm = SVC(probability=True)
svm_ada = AdaBoostClassifier(base_estimator=svm)
svm_ada.fit(X_train_scaled, y_train)


AdaBoostClassifier(base_estimator=SVC(probability=True))

In [27]:

# Random Forest
rf = RandomForestClassifier()
rf_ada = AdaBoostClassifier(base_estimator=rf)
rf_ada.fit(X_train_scaled, y_train)

AdaBoostClassifier(base_estimator=RandomForestClassifier())

In [28]:
from sklearn.linear_model import Perceptron
# Naïve Bayes
nb = Perceptron()
nb_ada = AdaBoostClassifier(base_estimator=nb,algorithm='SAMME')
nb_ada.fit(X_train_scaled, y_train)


AdaBoostClassifier(algorithm='SAMME', base_estimator=Perceptron())

In [29]:
from sklearn.linear_model import LogisticRegression
# Logistic Regression
logreg = LogisticRegression(max_iter=1000)

# AdaBoost with Logistic Regression
logreg_ada = AdaBoostClassifier(base_estimator=logreg)
logreg_ada.fit(X_train_scaled, y_train)

AdaBoostClassifier(base_estimator=LogisticRegression(max_iter=1000))

In [30]:


# Bagging using the voting average technique

# Support Vector Machine (SVM)
svm_bagging = BaggingClassifier(base_estimator=svm, n_estimators=10)
svm_bagging.fit(X_train_scaled, y_train)

# Random Forest
rf_bagging = BaggingClassifier(base_estimator=rf, n_estimators=10)
rf_bagging.fit(X_train_scaled, y_train)

# Naïve Bayes
nb_bagging = BaggingClassifier(base_estimator=nb, n_estimators=10)
nb_bagging.fit(X_train_scaled, y_train)

logreg_bagging = BaggingClassifier(base_estimator=logreg, n_estimators=10)
logreg_bagging.fit(X_train_scaled, y_train)


BaggingClassifier(base_estimator=LogisticRegression(max_iter=1000))

In [31]:

# Make predictions on the test set
svm_ada_preds = svm_ada.predict(X_test_scaled)
rf_ada_preds = rf_ada.predict(X_test_scaled)
nb_ada_preds = nb_ada.predict(X_test_scaled)
logreg_ada_preds = logreg_ada.predict(X_test_scaled)

svm_bagging_preds = svm_bagging.predict(X_test_scaled)
rf_bagging_preds = rf_bagging.predict(X_test_scaled)
nb_bagging_preds = nb_bagging.predict(X_test_scaled)
logreg_bagging_preds = logreg_bagging.predict(X_test_scaled)



In [32]:
#total =  (svm_ada_preds+rf_ada_preds+nb_ada_preds+logreg_ada_preds+ svm_bagging_preds+rf_bagging_preds+nb_bagging_preds+logreg_bagging_preds)/8

In [33]:
from scipy.stats import mode

# Convert predictions to 1D arrays
svm_ada_preds = svm_ada_preds.ravel()
rf_ada_preds = rf_ada_preds.ravel()
nb_ada_preds = nb_ada_preds.ravel()
logreg_ada_preds = logreg_ada_preds.ravel()
svm_bagging_preds = svm_bagging_preds.ravel()
rf_bagging_preds = rf_bagging_preds.ravel()
nb_bagging_preds = nb_bagging_preds.ravel()
logreg_bagging_preds = logreg_bagging_preds.ravel()

# Ensemble predictions using voting average technique
ensemble_preds = mode([svm_ada_preds, rf_ada_preds, nb_ada_preds, logreg_ada_preds,
                       svm_bagging_preds, rf_bagging_preds, nb_bagging_preds, logreg_bagging_preds], axis=0)[0]

ensemble_preds = ensemble_preds.reshape(y_test.shape)

# Calculate accuracy
accuracy = accuracy_score(y_test, ensemble_preds)
print("Accuracy:", accuracy)


Accuracy: 0.8685661764705882


C:\Users\HP\AppData\Local\Temp\ipykernel_648\2400068727.py:14: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  ensemble_preds = mode([svm_ada_preds, rf_ada_preds, nb_ada_preds, logreg_ada_preds,


In [27]:
ensemble_preds==1

array([False, False, False, ...,  True,  True,  True])

In [28]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, ensemble_preds)
recall = recall_score(y_test, ensemble_preds)
f1 = f1_score(y_test, ensemble_preds)


In [29]:
precision 

0.8511904761904762

In [30]:
recall

0.6982421875

In [31]:
f1

0.7671673819742489

In [32]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, ensemble_preds)
cm

array([[899, 125],
       [309, 715]], dtype=int64)

In [31]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [20]:
# Create the ANN model
model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train_scaled, y_train, epochs=200, batch_size=32, verbose=1)

Epoch 1/200
255/255 [==============================] - 1s 2ms/step - loss: 0.5738 - accuracy: 0.7180
Epoch 2/200
255/255 [==============================] - 0s 2ms/step - loss: 0.4580 - accuracy: 0.7938
Epoch 3/200
255/255 [==============================] - 0s 2ms/step - loss: 0.4400 - accuracy: 0.7984
Epoch 4/200
255/255 [==============================] - 0s 2ms/step - loss: 0.4314 - accuracy: 0.8024
Epoch 5/200
255/255 [==============================] - 0s 2ms/step - loss: 0.4241 - accuracy: 0.8089
Epoch 6/200
255/255 [==============================] - 0s 2ms/step - loss: 0.4185 - accuracy: 0.8126
Epoch 7/200
255/255 [==============================] - 0s 2ms/step - loss: 0.4135 - accuracy: 0.8143
Epoch 8/200
255/255 [==============================] - 0s 2ms/step - loss: 0.4095 - accuracy: 0.8189
Epoch 9/200
255/255 [==============================] - 0s 2ms/step - loss: 0.4060 - accuracy: 0.8198
Epoch 10/200
255/255 [==============================] - 0s 2ms/step - loss: 0.4008 - accura

255/255 [==============================] - 0s 1ms/step - loss: 0.2211 - accuracy: 0.9167
Epoch 161/200
255/255 [==============================] - 0s 1ms/step - loss: 0.2210 - accuracy: 0.9156
Epoch 162/200
255/255 [==============================] - 0s 2ms/step - loss: 0.2200 - accuracy: 0.9165
Epoch 163/200
255/255 [==============================] - 0s 2ms/step - loss: 0.2195 - accuracy: 0.9147
Epoch 164/200
255/255 [==============================] - 0s 2ms/step - loss: 0.2202 - accuracy: 0.9179
Epoch 165/200
255/255 [==============================] - 0s 2ms/step - loss: 0.2175 - accuracy: 0.9202
Epoch 166/200
255/255 [==============================] - 0s 2ms/step - loss: 0.2173 - accuracy: 0.9179
Epoch 167/200
255/255 [==============================] - 0s 2ms/step - loss: 0.2183 - accuracy: 0.9183
Epoch 168/200
255/255 [==============================] - 0s 1ms/step - loss: 0.2164 - accuracy: 0.9189
Epoch 169/200
255/255 [==============================] - 0s 2ms/step - loss: 0.2164 - a

In [21]:
# Make predictions on the test set
y_pred_proba = model.predict(X_test_scaled)

print(y_pred_proba )
y_pred = np.round(y_pred_proba).flatten()
print(y_pred)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

34/34 [==============================] - 0s 1ms/step
[[1.4328962e-06]
 [6.8682784e-01]
 [4.6877126e-06]
 ...
 [5.4557820e-08]
 [1.5564059e-06]
 [4.3087726e-07]]
[0. 1. 0. ... 0. 0. 0.]
Accuracy: 0.8419117647058824


In [22]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print("precision: ", precision)
print("recall: ", recall)
print("F1 score: ", f1)

precision:  0.23857868020304568
recall:  0.6811594202898551
F1 score:  0.3533834586466165


In [23]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[869, 150],
       [ 22,  47]], dtype=int64)

In [32]:
from sklearn.model_selection import StratifiedKFold

# Define the number of folds for cross-validation
n_folds = 5

# Initialize lists to store the evaluation results
accuracy_scores = []
loss_scores = []

# Perform cross-validation
skf = StratifiedKFold(n_splits=n_folds, shuffle=True)
for train_index, val_index in skf.split(X_train_scaled, y_train):
    # Split the data into training and validation sets for each fold
    X_train_fold, X_val_fold = X_train_scaled[train_index], X_train_scaled[val_index]
    y_train_fold, y_val_fold = y_train[train_index], y_train[val_index]

    # Create the ANN model
    model = Sequential()
    model.add(Dense(16, activation='sigmoid', input_shape=(X_train.shape[1],)))
    model.add(Dense(8, activation='sigmoid'))
    model.add(Dense(1, activation='sigmoid'))

    # Compile the model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

    # Train the model
    model.fit(X_train_fold, y_train_fold, epochs=200, batch_size=32, verbose=0)

    # Evaluate the model on the validation set
    loss, accuracy = model.evaluate(X_val_fold, y_val_fold, verbose=0)

    # Store the evaluation scores
    loss_scores.append(loss)
    accuracy_scores.append(accuracy)

# Calculate the mean and standard deviation of the evaluation scores
mean_loss = np.mean(loss_scores)
mean_accuracy = np.mean(accuracy_scores)
std_loss = np.std(loss_scores)
std_accuracy = np.std(accuracy_scores)

# Print the results
print("Cross-Validation Results:")
print("Loss: {:.4f} (+/- {:.4f})".format(mean_loss, std_loss))
print("Accuracy: {:.4f} (+/- {:.4f})".format(mean_accuracy, std_accuracy))


Cross-Validation Results:
Loss: 0.3917 (+/- 0.0108)
Accuracy: 0.8290 (+/- 0.0069)


In [129]:
import xgboost as xgb
# Create the XGBoost classifier
xgb_model = xgb.XGBClassifier()

# Train the model
xgb_model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = xgb_model.predict(X_test_scaled)

In [130]:
# Get predicted probabilities for the positive class
y_prob = xgb_model.predict_proba(X_test_scaled)[:, 1]

# Define a new threshold
new_threshold = 0.7  # Adjust this value as per your requirements

# Convert probabilities to binary predictions based on the new threshold
y_pred = np.where(y_prob >= new_threshold, 1, 0)

In [131]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6328125


In [132]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print("precision: ", precision)
print("recall: ", recall)
print("F1 score: ", f1)

precision:  0.925
recall:  0.2890625
F1 score:  0.44047619047619047


In [133]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1000,   24],
       [ 728,  296]], dtype=int64)

In [28]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import SGDClassifier, Perceptron, PassiveAggressiveClassifier, RidgeClassifierCV, LogisticRegressionCV
from sklearn.ensemble import AdaBoostClassifier, BaggingClassifier, ExtraTreesClassifier, GradientBoostingClassifier, HistGradientBoostingClassifier
from sklearn.svm import NuSVC, LinearSVC
from sklearn.calibration import CalibratedClassifierCV
from sklearn.neighbors import NearestCentroid
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.naive_bayes import MultinomialNB, ComplementNB, BernoulliNB, CategoricalNB
from sklearn.neural_network import MLPClassifier
from sklearn.semi_supervised import LabelPropagation, LabelSpreading
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.ensemble import StackingClassifier
from lightgbm import LGBMClassifier

In [135]:
# Define classifiers
classifiers = {
    'SGD': SGDClassifier(),
    'Perceptron': Perceptron(),
    'AdaBoost': AdaBoostClassifier(),
    #'XGBoost': XGBClassifier(),
    'PAC': PassiveAggressiveClassifier(),
    'RC': RidgeClassifierCV(),
    #'Nu-SVC': NuSVC(),
    'LSVC': LinearSVC(),
    'CCCV': CalibratedClassifierCV(),
    'NC': NearestCentroid(),
    'GPC': GaussianProcessClassifier(),
    'MNB': MultinomialNB(),
    'ComplementNB': ComplementNB(),
    'BNB': BernoulliNB(),
    'CategoricalNB': CategoricalNB(),
    'Bagging': BaggingClassifier(),
    'ET': ExtraTreesClassifier(),
    'GBC': GradientBoostingClassifier(),
    'HGBC': HistGradientBoostingClassifier(),
    #'OVsRC': OneVsRestClassifier(),
    'MLP': MLPClassifier(),
    'LP': LabelPropagation(),
    'LS': LabelSpreading(),
    #'Stacking': StackingClassifier(),
    'RCCV': RidgeClassifierCV(),
    'LRCV': LogisticRegressionCV(),
    'LDA': LinearDiscriminantAnalysis(),
    'QDA': QuadraticDiscriminantAnalysis(),
    'LGBM': LGBMClassifier()
}

# Initialize result dataframe
results = pd.DataFrame(columns=['Classifier', 'Accuracy', 'Precision', 'Recall', 'F1 Score'])

# Iterate over classifiers
for name, clf in classifiers.items():
    clf.fit(X_train_scaled, y_train)
    y_pred = clf.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    print(results)
    results = results.append({'Classifier': name, 'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'F1 Score': f1}, ignore_index=True)

# Print results
print(results)

Empty DataFrame
Columns: [Classifier, Accuracy, Precision, Recall, F1 Score]
Index: []


C:\Users\HP\AppData\Local\Temp\ipykernel_12000\3353424722.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append({'Classifier': name, 'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'F1 Score': f1}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_12000\3353424722.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append({'Classifier': name, 'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'F1 Score': f1}, ignore_index=True)


  Classifier  Accuracy Precision    Recall  F1 Score
0        SGD  0.802246  0.869773  0.710938  0.782375
   Classifier  Accuracy Precision    Recall  F1 Score
0         SGD  0.802246  0.869773  0.710938  0.782375
1  Perceptron  0.822754  0.862788  0.767578  0.812403
   Classifier  Accuracy Precision    Recall  F1 Score
0         SGD  0.802246  0.869773  0.710938  0.782375
1  Perceptron  0.822754  0.862788  0.767578  0.812403
2    AdaBoost  0.773926  0.822785  0.698242  0.755415
   Classifier  Accuracy Precision    Recall  F1 Score
0         SGD  0.802246  0.869773  0.710938  0.782375
1  Perceptron  0.822754  0.862788  0.767578  0.812403
2    AdaBoost  0.773926  0.822785  0.698242  0.755415
3         PAC   0.73291  0.774453  0.657227  0.711041


C:\Users\HP\AppData\Local\Temp\ipykernel_12000\3353424722.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append({'Classifier': name, 'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'F1 Score': f1}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_12000\3353424722.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append({'Classifier': name, 'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'F1 Score': f1}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_12000\3353424722.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append({'Classifier': name, 'Accuracy': accuracy, 'Precision': precision, 'Recall': recall

   Classifier  Accuracy Precision    Recall  F1 Score
0         SGD  0.802246  0.869773  0.710938  0.782375
1  Perceptron  0.822754  0.862788  0.767578  0.812403
2    AdaBoost  0.773926  0.822785  0.698242  0.755415
3         PAC   0.73291  0.774453  0.657227  0.711041
4          RC  0.786133  0.836782  0.710938  0.768743


C:\Users\HP\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\HP\AppData\Local\Temp\ipykernel_12000\3353424722.py

   Classifier  Accuracy Precision    Recall  F1 Score
0         SGD  0.802246  0.869773  0.710938  0.782375
1  Perceptron  0.822754  0.862788  0.767578  0.812403
2    AdaBoost  0.773926  0.822785  0.698242  0.755415
3         PAC   0.73291  0.774453  0.657227  0.711041
4          RC  0.786133  0.836782  0.710938  0.768743
5        LSVC  0.797363  0.834983  0.741211  0.785308
   Classifier  Accuracy Precision    Recall  F1 Score
0         SGD  0.802246  0.869773  0.710938  0.782375
1  Perceptron  0.822754  0.862788  0.767578  0.812403
2    AdaBoost  0.773926  0.822785  0.698242  0.755415
3         PAC   0.73291  0.774453  0.657227  0.711041
4          RC  0.786133  0.836782  0.710938  0.768743
5        LSVC  0.797363  0.834983  0.741211  0.785308
6        CCCV  0.795898  0.832237  0.741211  0.784091
   Classifier  Accuracy Precision    Recall  F1 Score
0         SGD  0.802246  0.869773  0.710938  0.782375
1  Perceptron  0.822754  0.862788  0.767578  0.812403
2    AdaBoost  0.773926  0.8

C:\Users\HP\AppData\Local\Temp\ipykernel_12000\3353424722.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append({'Classifier': name, 'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'F1 Score': f1}, ignore_index=True)


ValueError: Negative values in data passed to MultinomialNB (input X)

In [136]:
results

Classifier  Accuracy Precision    Recall  F1 Score
0         SGD  0.802246  0.869773  0.710938  0.782375
1  Perceptron  0.822754  0.862788  0.767578  0.812403
2    AdaBoost  0.773926  0.822785  0.698242  0.755415
3         PAC   0.73291  0.774453  0.657227  0.711041
4          RC  0.786133  0.836782  0.710938  0.768743
5        LSVC  0.797363  0.834983  0.741211  0.785308
6        CCCV  0.795898  0.832237  0.741211  0.784091
7          NC  0.774414  0.815022  0.709961  0.758873
8         GPC  0.717773  0.813202   0.56543  0.667051

In [19]:
# Define the parameter grid for hyperparameter tuning
from sklearn.linear_model import Perceptron
from sklearn.model_selection import GridSearchCV, train_test_split
param_grid = {
    'penalty': ['l1', 'l2', 'elasticnet'],
    'alpha': [0.0001, 0.001, 0.01, 0.1],
    'max_iter': [100, 500, 1000],
    'eta0': [0.1, 0.01, 0.001]
}

# Create the Perceptron model
model = Perceptron()

# Perform Grid Search with cross-validation
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Get the best model and its hyperparameters
best_model = grid_search.best_estimator_
best_params = grid_search.best_params_

In [20]:
best_params

{'alpha': 0.001, 'eta0': 0.1, 'max_iter': 100, 'penalty': 'l1'}

In [22]:
#Make predictions on the test set
from sklearn.metrics import precision_score, recall_score, f1_score

y_pred = best_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Evaluation on Test Set:")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-Score: {f1}")
print("Best Hyperparameters:", best_params)

Evaluation on Test Set:
Accuracy: 0.80078125
Precision: 0.7784810126582279
Recall: 0.8408203125
F1-Score: 0.8084507042253521
Best Hyperparameters: {'alpha': 0.001, 'eta0': 0.1, 'max_iter': 100, 'penalty': 'l1'}


In [23]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[779, 245],
       [163, 861]], dtype=int64)

In [24]:
##Voting Classifier

In [30]:
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
# Decision tree Algorithm
from sklearn.tree import DecisionTreeClassifier

In [31]:
from sklearn.metrics import confusion_matrix, recall_score, precision_score, f1_score, accuracy_score
from sklearn.metrics import classification_report

In [32]:
estimator = []
estimator.append(('Neural Network', MLPClassifier(max_iter = 10000) ))
estimator.append(('LP', LabelPropagation()))
estimator.append((  'LS', LabelSpreading()))
estimator.append(('RandomForest', DecisionTreeClassifier(criterion = 'entropy', random_state = 42) ))
#estimator.append(('KNN', KNeighborsClassifier() ))
estimator.append(( 'LGBM', LGBMClassifier()))
estimator.append(( 'HGBC', HistGradientBoostingClassifier() ))
estimator.append(('ET', ExtraTreesClassifier() ))
estimator.append(( 'GBC', GradientBoostingClassifier()))
estimator.append(('Bagging', BaggingClassifier()))

In [33]:
VC_hard = VotingClassifier(estimators = estimator, voting ='hard')
VC_hard.fit(X_train_scaled, y_train)
y_pred = VC_hard.predict(X_test_scaled)

In [34]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.60400390625


In [35]:
cm = confusion_matrix(y_test, y_pred)

VC_hard_Recall = recall_score(y_test, y_pred)
VC_hard_Precision = precision_score(y_test, y_pred)
VC_hard_f1 = f1_score(y_test, y_pred)
VC_hard_accuracy = accuracy_score(y_test, y_pred)

print(cm)

[[988  36]
 [775 249]]
